act_obj.c, merc.h, update.c
Awarding quest points for crafting
=> Crafting awards

gifts.c
Also changed the messages given when in homid form or silver claws is already active.
=> Silverclaws crash bugfix and error messages

fight.c
group_gain: fixed ch to gch (closes #282)
=> group_gain: fixed ch to gch (closes #282)

interp.c
Adds ability to use 'help' while earthmeld, trapped, etc.
=> help access added (closes #287)

const.c, db.c, handler.c, merc.h, rote.c
new shortcut for living beings, allow change sex to be referenced with new gsn, sense life recoded with visuals and more detailed life info
=> Senselife recode for visual and info (closes #289)

garou.c, gifts.c, tables.c
Gift allows the Furies to change sex (illusion) to appear male.  Can be combined with mobprogs for best effects.
=> Mans skin (new black fury gift)  rank 1  (closes #293)

const.c, gifts.c, tables.c
mimics immortal 'peace' command, with cost and limits.
=> Distractthefool -  New Gift  Fianna Rank 1 (closes #295)

act_info.c, gifts.c, tables.c
=> scent of true form

comm.c
=> Battleprompt

act_obj.c, gifts.c, tables.c
=> Speechoftheworld

act_skills.c, cmdtable.c, const.c, db.c, interp.h, merc.h
Adding cue, it is added to act_skills, cmd_table, const, db, merc.h, and interp.h
=> Adding cue

const.c, db.c, gifts.c, magic.h, merc.h, tables.c
Borrowed from modern Glass Walkers
=> New Warders of Men Gift - Steel Fur

act_obj.c
Less of true Identify, now gives vague info
=> Lore Recode

act_info.c, const.c, ritual.c
Prelim for future Garou Fetish system
=> Bind rework

act_info.c, disciplines.c, special.c, update.c
Fixing crash caused by looking at your affects if a mob 'Awed' you.
=> Mob awe crash

const.c, db.c, magic.c, merc.h
Tweaked spells cast by mobs, or used on items, to better fit with Haven.
=> Spelltweaks: QoL on obj/mob spells

act_wiz.c
Piggyback off the 'mset' code.
=> Ability for Immortals to set sire/mentor

act_info.c, const.c, fight.c, gifts.c, handler.c, tables.c
New Gifts:
Attunement, Doppelganger
Empathy, Exceptional Swordplay
QoL Gift:
Hare's Leap
'Gifts' Command QoL:
Usable by all to see every Gift in database, and give details (Rank/Breed/Auspice/Tribe), and whether coded or not.  
Also give ability to filter by B/A/T.
=> New Gifts, New option on 'Gifts' command

cmdtable.c, comm.c, const.c, db.c, disciplines.c, fight.c, interp.h, merc.h, tables.c
=> New Discipline - Serpentis

act_info.c, const.c, db.c, fight.c, merc.h, special.c, tables.c, update.c
Added: Animalism, Fortitude, Protean, Gangrel, Ventrue
Updated: Potence
=> Discipline Spec programs

act_comm.c, cmdtable.c, interp.h, merc.h, mob_cmds.c, mob_prog.c, olc_act.c, tables.c
'talk (mob)'    to trigger mprog.
=> New Mobprog Trigger: TALK

act_skills.c
Fixes vigor to use at lvl 20 properly, instead of level 1.
=> Vigor Bugfix

act_wiz.c, cmdtable.c, interp.h
Force player/mob across Gauntlet, to/from Umbra.
=> Immortal Command:  Cross gauntlet

charsheet.c, merc.h, tables.c, update.c
=> Ghoul Update

const.c, disciplines.c, gifts.c, rote.c, tables.c
Calm the Savage Beast (Homid 3)
Aura of Confidence (Shadow Lord 1)
Clap of Thunder (Shadow Lord 2)
=> New Gifts Coded
